######################################################################
# Automatically generated by qmake (3.0) ? 8 27 16:56:34 2016
######################################################################

TEMPLATE = app
TARGET = sudoku
INCLUDEPATH += .

# Input
SOURCES += sudoku.cpp
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
