######################################################################
# Automatically generated by qmake (3.0) ? 8 27 16:50:53 2016
######################################################################

TEMPLATE = app
TARGET = layout
INCLUDEPATH += .

# Input
SOURCES += layout.cpp
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
