######################################################################
# Automatically generated by qmake (3.0) ? 8 27 07:09:28 2016
######################################################################

TEMPLATE = app
TARGET = button
INCLUDEPATH += .

# Input
SOURCES += button.cpp
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
