######################################################################
# Automatically generated by qmake (3.0) ? 8 27 07:00:16 2016
######################################################################

TEMPLATE = app
TARGET = dialog
INCLUDEPATH += .

# Input
HEADERS += main.h
SOURCES += 01.cpp
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
