######################################################################
# Automatically generated by qmake (3.0) ? 8 27 07:13:22 2016
######################################################################

TEMPLATE = app
TARGET = disconnect
INCLUDEPATH += .

# Input
SOURCES += disconnect.cpp
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
