######################################################################
# Automatically generated by qmake (3.0) ? 8 27 07:35:02 2016
######################################################################

TEMPLATE = app
TARGET = event
INCLUDEPATH += .

# Input
SOURCES += event.cpp
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
