######################################################################
# Automatically generated by qmake (3.0) ? 8 13 09:30:51 2016
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
